### ISSUE TITLE
Compact find bar overlaps sidebar when moved to right

### ISSUE THREAD

**Issue by Keith94** [Timvde/UserChrome-Tweaks#44]
Regarding the style: [compact-findbar-on-top.css](https://github.com/Timvde/UserChrome-Tweaks/blob/master/findbar/compact-findbar-on-top.css)

![image](https://user-images.githubusercontent.com/5490615/30780457-f894cf9a-a0bf-11e7-945d-522a066d1a30.png)

**Comment by Madis0** [comment]
That is a bit hard to fix, since the position is fixed and even if I somehow set a second position for when sidebar is opened, you can adjust sidebar's width too, making it still "break".

As a workaround, I would suggest setting `right: 1em;` to a value you prefer, such as _19em_.

**Comment by Timvde** [comment]
Alternatively, would `left: 1em` move it to the top left?

**Comment by Madis0** [comment]
In that case, one can remove that line entirely (default is left with zero margin).

**Comment by Timvde** [comment]
I suppose that there is no way to check in CSS whether the sidebar is open, and on which side it is?

**Comment by Madis0** [comment]
I guess it might be, but I don't have the time/tools to find out at the moment.

**Comment by Thorin-Oakenpants** [comment]
OT: please delete when dealt with:

https://www.reddit.com/r/firefox/comments/77r8en/is_the_prefsjs_the_only_way_to_input_multiple/doo9hbe/

I do not have a reddit account, so if you would be so kind as to inform OP... you can create multiple `*.js` files rather than just use a single user.js - rather than regurgitate it all here, I'll just link to this -> https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.5-Keeping-Up-To-Date

I do not know if `user.js` must be present, probably (I haven't tested)! Even if it just contains a single pref. I do not know the order in which js files are read and applied in `/profile/preferences/` - the consensus was to just make sure you don't double up on prefs in them

**Comment by Madis0** [comment]
I have now found out that there is a parameter called _ordinal_ that says whether the sidebar is on the left or right, so as an example one could do this:

```
#sidebar-box[ordinal="2"]{ /* red if left */
  background-color: red !important;
}

#sidebar-box[ordinal="4"]{ /* green if right */
  background-color: green !important;
}
```

Only question is, how to use that to adjust the find bar? Something like

```
#sidebar-box[ordinal="4"] > .browserContainer > findbar {
  left: 0em !important;
}
```

didn't do the trick.

**Comment by Timvde** [comment]
I think some magic with the `:has` selector could do the trick: https://developer.mozilla.org/en-US/docs/Web/CSS/:has

But that compatibility table looks kinda depressing :P I don't think this is currently possible.
