### ISSUE TITLE
My styles

### ISSUE THREAD

**Issue by Madis0** [Timvde/UserChrome-Tweaks#5]
Here is a list of my styles that should work in Firefox 57, please add them to this repository. Maybe you can get the original screenshots with some hacking around, or just make new ones. 

https://userstyles.org/styles/146846/android-style-tabs-fx-57 - androidStyleTabs.css

https://userstyles.org/styles/121537/compact-find-bar-fx-50 - compactFindBar.css

https://userstyles.org/styles/140689/gray-flat-tab-icons-fx - flatTabIcons.css

https://userstyles.org/styles/92774/hide-back-forward-in-maximized-window-fx-42 - hideBackForward.css

https://userstyles.org/styles/146845/merge-tabs-and-navigation-bar-fx-57 - mergeTabsNavigation.css

https://userstyles.org/styles/121010/move-identity-box-to-the-right-fx-50 -identityBoxRight.css

https://userstyles.org/styles/146843/prevent-tab-overflow-fx - preventTabOverflow.css

https://userstyles.org/styles/141315/private-browsing-address-bar-background - privateAddressBackground.css

**Comment by Timvde** [comment]
I have licensed this repository als GPLv3. Your styles are in the public domain. If I'm not mistaken, this means that I am free to relicense it as I wish. However, if you are not okay with relicensing, I will instead add a header to each file stating explicitly that this code is in the public domain. I believe that should cover it in any case.

I have now added a `CONTRIBUTING.md` file to the repository stating this relicensing issue. However, since your issue was created before I added this file, I wanted to explicitly point it out to you.

**Comment by Madis0** [comment]
I want to keep things simple so I am okay with GPL-V3 for all my styles. 

I will explicitly mention when I want an another license for a specific style.

**Comment by Madis0** [comment]
One thing to note - the comments for inline properties (inside brackets) are supposed to be in the end of a code line, instead of next row - us.o messed with the spaces.

Also I've rewritten compactFindBar because you couldn't see full code when using style options in us.o: https://gist.github.com/Madis0/7bdec522c5577021ea9043687240588a

**Comment by Madis0** [comment]
Here's another style to upload: https://userstyles.org/styles/142555/hide-lock-for-https-autohide-i-icon-fx-52 - hideLockAutohideInfo.css

**Comment by Timvde** [comment]
> https://userstyles.org/styles/146846/android-style-tabs-fx-57 - androidStyleTabs.css

I don't really see a difference in the tab colour. Could you elaborate what "transparent" means exactly? I tested on Linux with default theme, dark theme and a persona. The white line is clear :)

> https://userstyles.org/styles/121537/compact-find-bar-fx-50 - compactFindBar.css

I wanted to split this in two: a compact find bar and a top find bar. However, since I'm not really good with CSS, I didn't manage to :( Would you maybe want to split this for me? If not, I'll include it as-is and create an issue, hoping someone else will pick it up.

> https://userstyles.org/styles/140689/gray-flat-tab-icons-fx - flatTabIcons.css

I think it is prettier with `contrast(1)` instead of `contrast(2)`, so I am inclined to change this. If you disagree, I will leave your default value.

In the future, I am planning to make a Python script to manage CSS files in this repository. At that point, I can ship a config file using CSS variables. I think this is a great example where this can pay off.

> https://userstyles.org/styles/92774/hide-back-forward-in-maximized-window-fx-42 - hideBackForward.css

Why only in a maximized window? I have no problem including the style as-is, I'm just curious.

> https://userstyles.org/styles/146845/merge-tabs-and-navigation-bar-fx-57 - mergeTabsNavigation.css

This one sadly looks a little broken for me :( The navigation toolbar is too high to contain tabs. I tried playing with density settings, but that didn't solve it. Also the hamburger menu seems to have the wrong size. (KDE5) Apart from this, nice style, kudos!

> https://userstyles.org/styles/121010/move-identity-box-to-the-right-fx-50 -identityBoxRight.css

I made this into two styles.

> https://userstyles.org/styles/146843/prevent-tab-overflow-fx - preventTabOverflow.css

Since you're linking to superuser.com, I'll give attribution to both Jeremy Sturdivant and you.

> https://userstyles.org/styles/141315/private-browsing-address-bar-background - privateAddressBackground.css

I have chosen to hardcode a black background with white text. However, in Firefox 56 and lower, this makes the identity icon not visible. Adding `#identity-box { filter: invert(1); }` seems to mostly fix the issue, except on the `about:privatebrowsing` homepage. Any clue?

**Comment by Madis0** [comment]
>I don't really see a difference in the tab colour. Could you elaborate what "transparent" means exactly? I tested on Linux with default theme, dark theme and a persona. The white line is clear :)

It should remove the white active tab background, keeping just the line (and moving it to the bottom and coloring white). Maybe I need to test it more though. 
The goal is reimplementing this https://userstyles.org/styles/138013/android-style-tabs-fx-56 for 57+ and reusing new UI elements while at it.

>I wanted to split this in two: a compact find bar and a top find bar. 

I think the ordinal group moves it up and position: fixed compacts it. I can't test style changes right now unfortunately 😞 

>I think it is prettier with contrast(1) instead of contrast(2)

The goal was making the icons look like gray outlines, to better match the rest of the toolbar. From what I remember, when reducing the contrast, it increased the amount of details in the icon. 

>At that point, I can ship a config file using CSS variables.

Sounds cool!

>Why only in a maximized window?

It's meant for extensions like MileWideBack, where it's easy to hit the edge on a maximized window, but hard to aim on a restored window. 

>This one sadly looks a little broken for me :(
Yeah, it's not completely finished but it looked usable when I last tested it. It is based on this: https://www.reddit.com/r/firefox/comments/6qbzz0/replacement_for_ctr_functionality_address_bar/dkw78s1/?context=3

>this makes the identity icon not visible.
Yeah, I haven't bothered to fix that yet, as I didn't really care for the info button. 😁

**Comment by Timvde** [comment]
> It should remove the white active tab background, keeping just the line

Might be something Windows-only? I'm on Linux.

> I think the ordinal group moves it up and position: fixed compacts it. I can't test style changes right now unfortunately 😞

I'll play around with it some more. Thanks for the hint!

> From what I remember, when reducing the contrast, it increased the amount of details in the icon.

It does, but icons became completely unrecognizable for me. Like I said, I'd prefer to change the contrast to 1, but if you wish it to be 2, I'll leave it as it.

> It's meant for extensions like MileWideBack, where it's easy to hit the edge on a maximized window, but hard to aim on a restored window.

I see, that does make sense, thanks!

> Yeah, it's not completely finished but it looked usable when I last tested it.

I'll try playing around with it some more, thank you for linking to the source. I'll also add /u/It_Was_The_Other_Guy as a contributor.

> Yeah, I haven't bothered to fix that yet, as I didn't really care for the info button. 😁

I understand, but I'd like to publish finished styles... :) Although, since I can't fix it, if you aren't planning to, I'll just create an issue and hope someone else picks it up :)

**Comment by Timvde** [comment]
> I think the ordinal group moves it up and position: fixed compacts it.

Having only `position: fixed` sadly breaks the find bar (it doesn't show at all) without also moving it to the top... :/

**Comment by Madis0** [comment]
>Might be something Windows-only? I'm on Linux.

Me too, using GNOME with Adapta theme. Haven't tried on Windows yet. 

>It does, but icons became completely unrecognizable for me.

Do they not look like the screenshot? Maybe Nightly changed something.

>I understand, but I'd like to publish finished styles... :) 

Or you could make a "WIP" folder? 😁 But yeah, an issue would make sense for now, maybe I'll get around it someday if people want the style.

**Comment by Timvde** [comment]
So, if I'm not mistaken, the only one that I didn't merge yet, is:

https://userstyles.org/styles/146845/merge-tabs-and-navigation-bar-fx-57 - mergeTabsNavigation.css

**Comment by Madis0** [comment]
Alright, I will work on it and probably make a proper pull request too.
